baseurl = "/"
languageCode = "en-us"
title = "workspacer"
theme = "kube"

googleAnalytics = "UA-130291662-1"

publishDir = "../out/docs/"

[[menu.main]]
    name = "quickstart"
    url = "/quickstart"
    weight = 2

[[menu.main]]
    name = "config"
    url = "/config"
    weight = 3

[[menu.main]]
    name = "keybinds"
    url = "/keybindings"
    weight = 4

[[menu.main]]
    name = "changelog"
    url = "/changelog"
    weight = 5

[[menu.extra]]
    name = "submit an issue"
    url = "https://github.com/rickbutton/workspacer/issues/new"