baseurl = "/"
languageCode = "en-us"
title = "workspacer"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "â†©"
publishDir = "../"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "workspacer"
    url = "/"
    weight = 1

[[menu.main]]
    name = "quickstart"
    url = "/quickstart"
    weight = 2

[[menu.main]]
    name = "config"
    url = "/config"
    weight = 3

[params]
    description = "a tiling window Manager for Windows"
    footer = "MIT Licensed | [github](https://github.com/rickbutton/workspacer)"
    custom_css = ["css/theme-override.css"]
