name: stable

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    # Build
    - uses: actions/checkout@v4
    - name: Get version
      run: Write-Output VERSION="$(([Xml] (Get-Content .\src\workspacer\workspacer.csproj)).Project.PropertyGroup.Version)" >> $env:GITHUB_ENV
    - name: Restore solution
      run: dotnet restore
    - name: Build project
      run: dotnet publish /p:DefineConstants=BRANCH_stable --configuration Release --no-restore
    - uses: actions/upload-artifact@v3
      with:
        name: Build
        path: .\src\workspacer\bin\Release\net7.0-windows\win10-x64\publish\
    - name: Build installer
      run: |
        $env:PATH += ";${env:WIX}bin" # Add to PATH
        .\scripts\buildinstaller.ps1 -buildDir .\src\workspacer\bin\Release\net7.0-windows\win10-x64\publish\ -version "$env:VERSION-stable"
    - uses: actions/upload-artifact@v3
      with:
        name: Setup
        path: .\out\workspacer-${{ env.VERSION }}-stable.msi
    
    # Release
    - name: Zip build output
      run: Compress-Archive -Path .\src\workspacer\bin\Release\net7.0-windows\win10-x64\publish\* -DestinationPath ".\out\workspacer-$env:VERSION-stable.zip"
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: workspacer ${{ env.VERSION }}
        body: https://www.workspacer.org/changelog
        files: |
          ./out/workspacer-${{ env.VERSION }}-stable.zip
          ./out/workspacer-${{ env.VERSION }}-stable.msi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
